### ISSUE TITLE
Fix source URLs and use latest releases

### ISSUE THREAD

**Issue by toni-sissala** [cessda/cessda.cdc.aggregator.devguide#13]
It seems this repo has not been updated for a while, since all the URLs still point to Bitbucket. I had a look at ReadTheDocs and it also has the old Bitbucket address. I will update the URLs and point them to new releases in requirements.txt. I think I can also manually build the docs to RTD, but I do not have rights to add a webhook to this Github project.

If there is need to automate the building of docs to RTD, either someone else should do it, or I need access to project settings in order to add a webhook (see https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html).

Any thoughts @matthew-morris-cessda ?

**Comment by matthew-morris-cessda** [comment]
I can give you permission to add webhooks to this repository so that the integration can be set up

**Comment by toni-sissala** [comment]
> I can give you permission to add webhooks to this repository so that the integration can be set up

Ok. Thanks!

**Comment by matthew-morris-cessda** [comment]
Permissions (hopefully) granted

**Comment by toni-sissala** [comment]
> Permissions (hopefully) granted

I don't see "Webhooks" under "Code and automation".  I can also see "Pages".

**Comment by matthew-morris-cessda** [comment]
OK, you should have permissions now

**Comment by toni-sissala** [comment]
> OK, you should have permissions now

Yes, I do. Thanks again!
